### ISSUE TITLE
Transcription viewer

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/digital-fauvel#11]
As seen in [screenshots](http://www.doc.gold.ac.uk/~mas01rf/DigitalFauvel/?page_id=26) from the original version of the edition, the transcriptions/translations of the text from the facsimiles should be lineated and positioned so as to correspond to the lineation and position of the original Old French text visible on the page. 

- [x] All annotations shown by default on load
- [x] No hover-triggered viewer
- [x] No editor
- [x] No borders on text, probably none on annotation, but yes on text region
- [x] Text centered within the selector target
- [x] Background color, opacity variable
- [x] Lines long enough to show all of text
- [x] Type optimized for legibility at middle sizes
- [x] Resize with rectangle container
- [x] Can be turned off globally, on globally
- [x] Several sets, user can switch between

**Comment by jamiefolsom** [comment]
Done.
